// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/chatservice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChatService_SayHi_FullMethodName = "/proto.ChatService/SayHi"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	SayHi(ctx context.Context, opts ...grpc.CallOption) (ChatService_SayHiClient, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) SayHi(ctx context.Context, opts ...grpc.CallOption) (ChatService_SayHiClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_SayHi_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceSayHiClient{stream}
	return x, nil
}

type ChatService_SayHiClient interface {
	Send(*Greeting) error
	Recv() (*Farewell, error)
	grpc.ClientStream
}

type chatServiceSayHiClient struct {
	grpc.ClientStream
}

func (x *chatServiceSayHiClient) Send(m *Greeting) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceSayHiClient) Recv() (*Farewell, error) {
	m := new(Farewell)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	SayHi(ChatService_SayHiServer) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) SayHi(ChatService_SayHiServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_SayHi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).SayHi(&chatServiceSayHiServer{stream})
}

type ChatService_SayHiServer interface {
	Send(*Farewell) error
	Recv() (*Greeting, error)
	grpc.ServerStream
}

type chatServiceSayHiServer struct {
	grpc.ServerStream
}

func (x *chatServiceSayHiServer) Send(m *Farewell) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceSayHiServer) Recv() (*Greeting, error) {
	m := new(Greeting)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHi",
			Handler:       _ChatService_SayHi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/chatservice.proto",
}
